// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180227.3

#pragma once
#include "winrt/Windows.UI.Xaml.Data.h"
#include "winrt/Windows.UI.Xaml.h"
#include "winrt/Windows.UI.Xaml.Controls.h"
#include "winrt/Bookstore.h"

namespace winrt::Bookstore::implementation {

template <typename D, typename... I>
struct WINRT_EBO BookSku_base : implements<D, Bookstore::IBookSku, Windows::UI::Xaml::Data::INotifyPropertyChanged, composing, I...>,
    impl::require<D, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2>,
    impl::base<D, Windows::UI::Xaml::DependencyObject>
{
    using base_type = BookSku_base;
    using class_type = Bookstore::BookSku;
    using implements_type = typename BookSku_base::implements_type;
    using implements_type::implements_type;
    using composable_base = Windows::UI::Xaml::DependencyObject;
    operator class_type() const noexcept
    {
        static_assert(std::is_same_v<typename impl::implements_default_interface<D>::type, impl::default_interface_t<class_type>>);
        class_type result{ nullptr };
        attach_abi(result, detach_abi(static_cast<impl::default_interface_t<class_type>>(*this)));
        return result;
    }

    hstring GetRuntimeClassName() const
    {
        return L"Bookstore.BookSku";
    }
    BookSku_base()
    {
        get_activation_factory<Windows::UI::Xaml::DependencyObject, Windows::UI::Xaml::IDependencyObjectFactory>().CreateInstance(*this, this->m_inner);
    }
};

}

#if defined(WINRT_FORCE_INCLUDE_BOOKSKU_XAML_G_H) || __has_include("BookSku.xaml.g.h")

#include "BookSku.xaml.g.h"

#else

namespace winrt::Bookstore::implementation
{
    template <typename D, typename... I>
    using BookSkuT = BookSku_base<D, I...>;
}

#endif
