// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180227.3

#pragma once
#include "winrt/impl/Windows.UI.Xaml.Data.0.h"
#include "winrt/impl/Windows.UI.Xaml.0.h"
#include "winrt/impl/Windows.UI.Xaml.Controls.0.h"
#include "winrt/impl/Bookstore.0.h"

WINRT_EXPORT namespace winrt::Bookstore {

struct WINRT_EBO IBookSku :
    Windows::Foundation::IInspectable,
    impl::consume_t<IBookSku>
{
    IBookSku(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IBookstoreViewModel :
    Windows::Foundation::IInspectable,
    impl::consume_t<IBookstoreViewModel>
{
    IBookstoreViewModel(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IMainPage :
    Windows::Foundation::IInspectable,
    impl::consume_t<IMainPage>
{
    IMainPage(std::nullptr_t = nullptr) noexcept {}
};

}
